export const techs = [
  {
    row: 1,
    col: 1,
    src: "/icons/nextjs.svg",
    title: "Next.js",
    desc: "A Modern React framework built by ",
    by: "@vercel",
    link: "https://vercel.com",
  },
  {
    row: 1,
    col: 2,
    src: "/icons/react.svg",
    title: "React",
    desc: "A JavaScript library for building user interfaces built by the developers at ",
    by: "@facebook",
    link: "https://react.dev",
  },
  {
    row: 1,
    col: 3,
    src: "/icons/tailwind.svg",
    title: "Tailwind CSS",
    desc: "A utility-first CSS framework built by ",
    by: "@tailwindcss",
    link: "https://tailwindcss.com",
  },
  {
    row: 2,
    col: 1,
    src: "/icons/typescript.svg",
    title: "TypeScript",
    desc: "A statically typed programming language that builds on JavaScript built by ",
    by: "@microsoft",
    link: "https://www.typescriptlang.org/",
  },
  {
    row: 2,
    col: 2,
    src: "/icons/nodejs.svg",
    title: "Node.js",
    desc: "A runtime environment to run JavaScript on servers ",
    by: "@nodejs",
    link: "https://nodejs.org/en",
  },
  {
    row: 2,
    col: 3,
    src: "/icons/supabase.svg",
    title: "Supabase",
    desc: "A modern database that hosts PostgreSQL databases ",
    by: "@supabase",
    link: "https://supabase.com/",
  },
  {
    row: 3,
    col: 1,
    src: "/icons/postgresql.svg",
    title: "PostgreSQL",
    desc: "A powerful, open source object-relational database system ",
    by: "@postgresql",
    link: "https://www.postgresql.org/",
  },
  {
    row: 3,
    col: 2,
    src: "/icons/electron.svg",
    title: "Electron",
    desc: "A framework for building cross-platform desktop applications with web technologies ",
    by: "@electron",
    link: "https://www.electronjs.org/",
  },
];
